server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3305/food_item
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
